### ISSUE TITLE
[python 3.5 - python 3.10 | Redis 6.2.0 - cluster] KeyError: 'redis_version'

### ISSUE THREAD

**Issue by TimoFrenzel** [rq/rq#1460]
Good day,
I get the following errors:

Traceback (most recent call last):
  File "/opt/tools/.\worker.py", line 19, in <module>
    result = q.enqueue(main)
  File "/usr/local/lib/python3.10/site-packages/rq/queue.py", line 419, in enqueue
    return self.enqueue_call(
  File "/usr/local/lib/python3.10/site-packages/rq/queue.py", line 366, in enqueue_call
    job = self.enqueue_job(job, at_front=at_front)
  File "/usr/local/lib/python3.10/site-packages/rq/queue.py", line 474, in enqueue_job
    job.save(pipeline=pipe)
  File "/usr/local/lib/python3.10/site-packages/rq/job.py", line 607, in save
    if self.get_redis_server_version() >= StrictVersion("4.0.0"):
  File "/usr/local/lib/python3.10/site-packages/rq/job.py", line 615, in get_redis_server_version
    self.redis_server_version = get_version(self.connection)
  File "/usr/local/lib/python3.10/site-packages/rq/utils.py", line 260, in get_version
    version_string = connection.info("server")["redis_version"]
KeyError: 'redis_version'

I've tested python 3.5 through 3.10.
Redis version 6.2.0 as cluster. (3 masters, 3 slaves)
(https://github.com/Grokzen/docker-redis-cluster)

**docker for redis:** 
```
  redis:
    image: grokzen/redis-cluster:latest
    container_name: redis
    restart: always
    ports:
      - '7000:7000'
      - '7001:7001'
      - '7002:7002'
      - '7003:7003'
      - '7004:7004'
      - '7005:7005'
    volumes:
    - ./bin/Redis:/data
    environment:
      - INITIAL_PORT=7000
      - MASTERS=3
      - SLAVES_PER_MASTER=1
    networks:
      - backend

networks:
  backend:
    driver: bridge
```

**my python code**

```
from rediscluster import RedisCluster
from rq import Queue

from sub import main

if __name__ == '__main__':
    startup_nodes = [{"host": "redis", "port": 7000, "db":0}]
    rc = RedisCluster(startup_nodes=startup_nodes, decode_responses=True, readonly_mode=False)

    #rc.set('test', 'dd')
    #print(rc.get('test'))

    q = Queue(connection=rc)
    result = q.enqueue(main)
    ```

greetz
