### ISSUE TITLE
Moving job to FailedJobRegistry (work-horse terminated unexpectedly; waitpid returned 6)

### ISSUE THREAD

**Issue by dmtyunin** [rq/rq#1720]
Hello, I get this error while trying to execute RDKit's method using rq job. RDKit throws some errors during execution. Like `non-ring atom 0 marked aromatic`
However, code **works well** despite the errors when being run **locally**.
I am using docker desktop for windows and run jobs in containers. But such job fail with the same error under GCP also.
Here is docker compose worker section:
```
   worker:
        env_file: .env
        build:
            context: .
            dockerfile: Dockerfile
        links:
            - redis
        command: rq worker --exception-handler worker.exception_handler.failed_exception_handler   --url redis://redis:6379 high default low
        cpu_shares: 10240 # means 10x more cpu time than 1024 cpu_shares
        mem_limit: 4g # strict upper limit
        memswap_limit: 6g # this means 2g of swap additional memory
        mem_reservation: 2g # minimal required amount of ram
        scale: 2
        restart: unless-stopped
```
Dockerfile uses `python:3.9-slim` as a base image. RQ version is `rq==1.11.1`

I have tried to increase memory limit but with no luck. Looks like child process receives signal 6 (SIGABRT) from the OS.
Is there a way to fix this somehow, any workaround?
